language: c

os:
    - linux
    - osx

sudo: required
dist: trusty

before_install:
    - git submodule update --init --recursive

install:
    - echo $TRAVIS_OS_NAME
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install -y libatlas-base-dev; fi
      # build and test library
    - make lib
    - (cd demo/; make; make demo_lib)

      # install dependencies for cli and testsuite
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install glib gsl argp-standalone; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libglib2.0-dev libatlas-base-dev libgsl0-dev; fi

script:
      # run test suite
    - (cd src/tests/; make all; make check)
      # run cli demo, linking fails on osx
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make cli; (cd demo/; make; make demo_cli); fi
